data:
  dataset: BGDataset
  dataname: lesion      # class name, used in dataloader (class name in *.json)
  data_dir: '/group/gaozht/Dataset/ISIC_noise2/'    # data directory
  aug_rot90: True   # rotate 90 degree              # data augmentation

  use_noisy_label: True
  load_clean_label: True
  dataset_noise_ratio: 0.3      # alpha & beta setting, load corresponding dataset
  sample_noise_ratio:  0.5

  load_superpixel_label: True   # load superpixel label

  em_save_pseudo_dir: '/group/gaozht/nlseg_exp/em_save_pseudo/'   # pseudo label dir for label refinement

model:
  network: 'Generic_UNet'
  pool_op_kernel_sizes: '[[2, 2], [2, 2], [2, 2], [2, 2], [2, 2]]'   # down [32, 32]
  conv_kernel_sizes: '[[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]]'

  deep_supervision: False
  use_finetune: False
  finetune_model_path: ''
  input_channel: 3      # 3 for color image, 1 for intensity image

train:
  n_epochs: 200
  n_batches: 250
  train_batch: 32
  valid_batch: 8

  loss_name: 'MultipleOutputLoss2'
  fg_weight: 1
  auto_weight: True
  with_dice_loss: 0

  optimizer: SGD
  momentum: 0.99
  lr: 5.0e-3
  lr_decay: 'constant'
  min_lr: 0.00

framework:

  # framework
  co_teaching: True # Use multi-view learning pipeline.
  warmup_epoch: 5 # Warmup epoch for selection ratio, follow the setting in Co-teaching.
  JoCoR: True # Use the agreement-based strategy during training.
  co_lambda: 0.65 # Weight for the regularization term used in JoCoR strategy.

  # selection
  # Original background/foreground remember_rate (aka. selection_rate).
  # We follow the previous works and assume them to be known.
  remember_rate_bg: 0.9796
  remember_rate_fg: 0.9335

  # correction
  sp_label_update_style: 'mean'
  conf_thres_fg: 0.5
  conf_thres_bg: 0.5

  # Update remember_rate after label refinement.
  Auto_E_step_epoch: True # Use the stopping criterion to automatic determine the updating epoch.
  E_update_remember_rate_linear: True
  # Update formula:  R = MAX(R, MIN(R*1.1,threshold)
  rem_linear_param: 1.1
  rem_thres: 0.9 # foreground threshold
  rem_thres_bg: 0.95 # background threshold

  # superpixel
  superpixel_select: True # Use superpixel-level selection during training.